language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
# command to install dependencies
install: "pip install --upgrade -r requirements.txt"
# command to run tests
script:
  - coverage run --source=marvin setup.py test
after_success: 
  - coveralls
