language: python

cache: pip

sudo: required

python:
- '2.7'

os:
- linux

services:
- postgresql
- memcached

addons:
  postgresql: '9.4'

notifications:
  slack:
    secure: FZXERPoPv4n52hBx3bvEjJ5T0Ey2Es7Sa7sd/MA4AMr7l1771YZ1VTLpVtpw4qJR8vrt4NtSFbBowJiovDmx6FCjEb/2N6RipjbLowAtFRqjalOGO3KZOi3UPeiytP/IYD1DG7YmeYJOL8aof2awns8ckAWRSz6HO3cDpqg+hycDXasZQdQfIKgY17UZvONBJZCZGeC3lMw4IrbhkfhW7aQvhUhcXDtfEyObNt2+FGE6y7WDeOEjtfArKc/Iz4gybWLkYPpA6rtQfQciQvpZv94sanxli8vq4mXIpu/dxn73jfKSYsYIl7+OYrXKJQBy/8muwwuSe2et15mG90KGUsDOJ+PXKCLOSl8JohO/pH0l3hZKno6nX7byL6orEbBuQjpMJO0QFUs7o6hLSv3q4tgtuV0M99I8UHcIgmBYL9oXI4BHIsSwreTXHfV/8LiuZfyaB2NzwKuRHQTZQfCD+ujqXaspyQX70Xew2L7rruRuBuKLTntgklMFtAPYJYbW/4z6HsZ//X6Z2BHwe0Etv4FZaKsf8IK81p//oYi/3kw2ENRYNARu0HzU0Edba6ugBPjzw6wFyWsL35IFTSosby50iAWo7xYfRXBv1kH0tPOcmPoJzFcrdAmvEqt6K8bNwqgx72/qsBp4fhmGfQM5G07dkyQM+hu+e9OPEfTwOo4=

branches:
- master

before_install:
- openssl aes-256-cbc -K $encrypted_34d6c89f986b_key -iv $encrypted_34d6c89f986b_iv -in etc/.netrc.enc -out ~/.netrc -d

install:
- pip install -r requirements.txt --quiet
- pip install psycopg2 --quiet
- pip install nose2 --quiet

before_script:
- export MANGA_LOCALHOST=1
- export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/python
- wget https://sas.sdss.org/marvin/data/local_mangadb_test.sql
- createdb -U postgres -T template0 manga
- createuser -U postgres -d -l -r -s Brian
- createuser -U postgres -d -l -r utahuser
- createuser -U postgres -g utahuser manga
- createuser -U postgres -g utahuser sdss
- createuser -U postgres -g utahuser u0857802
- createuser -U postgres -g utahuser u0707758
- createuser -U postgres -g utahuser u0931042
- psql -U postgres -d manga -c "set shared_buffers to '1792MB';" -c "set default_statistics_target to 100;"
- psql -U postgres -d manga -c "set effective_cache_size to '5376MB';" -c "set work_mem to '9175kB';"
- psql -U postgres -d manga -c "set maintenance_work_mem to '448MB';"
- psql -U postgres -d manga -c "set checkpoint_completion_target to 0.7;"
- pg_ctl restart
- pg_restore -Fc -j 8 -U postgres -d manga local_mangadb_test.sql

script:
- $TRAVIS_BUILD_DIR/bin/run_marvin -l -d -p 5000 > /dev/null & coverage run --source marvin setup.py nosetests

after_success:
- coveralls
