# Travis config file
#  - this is used for auto-testing everything on every git push
# ==================

language: python

sudo: required

python:
  - "2.7"

branches:
only:
  - master

# command to install dependencies
install:
  - pip install -r requirements.txt --quiet

# command to run tests
script:
  - coverage run --source marvin setup.py nosetests

after_success:
  - coveralls
